# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@alcalzone/jsonl-db-3.1.0" = {
      name = "_at_alcalzone_slash_jsonl-db";
      packageName = "@alcalzone/jsonl-db";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@alcalzone/jsonl-db/-/jsonl-db-3.1.0.tgz";
        sha512 = "Wc1nxOyJVBF0NWrG1X7SQcb6mWWtr2i9e1cOSHQsjmnHlBYlFoj82fsP1NCZrHdXBhqQyYpdXP8ZQ8zz0iddFQ==";
      };
    };
    "@alcalzone/pak-0.8.1" = {
      name = "_at_alcalzone_slash_pak";
      packageName = "@alcalzone/pak";
      version = "0.8.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@alcalzone/pak/-/pak-0.8.1.tgz";
        sha512 = "sPdxNxdXLH96kbyWLdIljVSIY2N6/qnPqkq5AlWvuizjGQUwHIUtWZHLss9XNDV/hY7YkgdIb9ILHbMTnRBxVQ==";
      };
    };
    "@alcalzone/proper-lockfile-4.1.3-0" = {
      name = "_at_alcalzone_slash_proper-lockfile";
      packageName = "@alcalzone/proper-lockfile";
      version = "4.1.3-0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@alcalzone/proper-lockfile/-/proper-lockfile-4.1.3-0.tgz";
        sha512 = "8mlX3l5Xc+pYyiK9G156NyMosNuvvukL+TtNMqw7ti2zgVpz+WqPMPb2J1WU8I03Jbm4cXF+Q0D53hWvQqLQ0Q==";
      };
    };
    "@colors/colors-1.5.0" = {
      name = "_at_colors_slash_colors";
      packageName = "@colors/colors";
      version = "1.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@colors/colors/-/colors-1.5.0.tgz";
        sha512 = "ooWCrlZP11i8GImSjTHYHLkvFDP48nS4+204nGb1RiX/WXYHmJA2III9/e2DWVabCESdW7hBAEzHRqUn9OUVvQ==";
      };
    };
    "@dabh/diagnostics-2.0.3" = {
      name = "_at_dabh_slash_diagnostics";
      packageName = "@dabh/diagnostics";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@dabh/diagnostics/-/diagnostics-2.0.3.tgz";
        sha512 = "hrlQOIi7hAfzsMqlGSFyVucrx38O+j6wiGOf//H2ecvIEqYN4ADBSS2iLMh5UFyDunCNniUIPk/q3riFv45xRA==";
      };
    };
    "@esm2cjs/cacheable-lookup-7.0.0" = {
      name = "_at_esm2cjs_slash_cacheable-lookup";
      packageName = "@esm2cjs/cacheable-lookup";
      version = "7.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@esm2cjs/cacheable-lookup/-/cacheable-lookup-7.0.0.tgz";
        sha512 = "5HzrA5N0lSMtx2RdXfD9Z4HUFaRGwVOFs7jsFG8jDivoZjYYwZFsSqvA17TaNZYFcwBrkSCqHlxDu2YDpjjUBA==";
      };
    };
    "@esm2cjs/cacheable-request-10.2.8" = {
      name = "_at_esm2cjs_slash_cacheable-request";
      packageName = "@esm2cjs/cacheable-request";
      version = "10.2.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@esm2cjs/cacheable-request/-/cacheable-request-10.2.8.tgz";
        sha512 = "mRdlYB2T9mitspkBM9LbmHjDgXBzwiRp891nSRQYsz6n74CI9MvdqLj/DaxipJ+WUAic3as/iq3DtS99vVLSdA==";
      };
    };
    "@esm2cjs/form-data-encoder-2.1.4" = {
      name = "_at_esm2cjs_slash_form-data-encoder";
      packageName = "@esm2cjs/form-data-encoder";
      version = "2.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@esm2cjs/form-data-encoder/-/form-data-encoder-2.1.4.tgz";
        sha512 = "HfuSoCMEgT5oHOwnN+o0f4Kzm+vBvRtddzJFFbLmawzPlFr3Djh2DHVDa2XpJCON4vjmd6RObd9R/oa0MvCLjg==";
      };
    };
    "@esm2cjs/got-12.5.3" = {
      name = "_at_esm2cjs_slash_got";
      packageName = "@esm2cjs/got";
      version = "12.5.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@esm2cjs/got/-/got-12.5.3.tgz";
        sha512 = "eI+5wDoF5bV4juELczVb65i+dFVPoQCq0XsnnBudzClQUYV+oScXVKt+LrToXO/1Vimfvt+EZoNmuwdQjz+Kkg==";
      };
    };
    "@esm2cjs/http-timer-5.0.1" = {
      name = "_at_esm2cjs_slash_http-timer";
      packageName = "@esm2cjs/http-timer";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@esm2cjs/http-timer/-/http-timer-5.0.1.tgz";
        sha512 = "BuqNhUgDz7pZffEwVXRXhRNb6l46CCu17knfUW7juP6H5ugqFFrLOcNiVjt66h4HjsHA0V5NKR7udA7kziqhoQ==";
      };
    };
    "@esm2cjs/is-5.3.0" = {
      name = "_at_esm2cjs_slash_is";
      packageName = "@esm2cjs/is";
      version = "5.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@esm2cjs/is/-/is-5.3.0.tgz";
        sha512 = "0v/CjH5qDJPbHrswb2T3BdHe0gDt6wKEaXGtAvrJgcJ3ptP6gdYWTflw3AJeCVZ42BK3/joU50ldz77Rikx5CQ==";
      };
    };
    "@esm2cjs/lowercase-keys-3.0.0" = {
      name = "_at_esm2cjs_slash_lowercase-keys";
      packageName = "@esm2cjs/lowercase-keys";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@esm2cjs/lowercase-keys/-/lowercase-keys-3.0.0.tgz";
        sha512 = "hqfn6odHNsUaMq2qptVKthPJCts6MxDf6eRIUl49NiN2CIu4CoaTGEswC+9WBg0hhzC+BqlfXTBNCgjp7OWyCQ==";
      };
    };
    "@esm2cjs/mimic-response-4.0.0" = {
      name = "_at_esm2cjs_slash_mimic-response";
      packageName = "@esm2cjs/mimic-response";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@esm2cjs/mimic-response/-/mimic-response-4.0.0.tgz";
        sha512 = "v0OcLK+2AmkCaUVirWNu+e8j8xd8jRIXhC/VbpFp4AkVXGovFspCmwx26IluxXiz8vHckP4uLy/GzMatiEqdLg==";
      };
    };
    "@esm2cjs/normalize-url-8.0.0" = {
      name = "_at_esm2cjs_slash_normalize-url";
      packageName = "@esm2cjs/normalize-url";
      version = "8.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@esm2cjs/normalize-url/-/normalize-url-8.0.0.tgz";
        sha512 = "9lrM8Q0ANSfM7ziVpNXEDKrVYcU4M3xIAUZWcvH9bY0fINBCkew1YBU1C1otfNoFDCERvCH0AkO70wkePdQwQw==";
      };
    };
    "@esm2cjs/p-cancelable-3.0.0" = {
      name = "_at_esm2cjs_slash_p-cancelable";
      packageName = "@esm2cjs/p-cancelable";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@esm2cjs/p-cancelable/-/p-cancelable-3.0.0.tgz";
        sha512 = "ETfhJRf8RpTHYua7nk9izoEYK4SbNBEvRoUF14VqSGgZt5qIOa5dnFsa1LBJ4Spw5UtjjD4LdwFW/93qnRFV0A==";
      };
    };
    "@esm2cjs/p-queue-7.3.0" = {
      name = "_at_esm2cjs_slash_p-queue";
      packageName = "@esm2cjs/p-queue";
      version = "7.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@esm2cjs/p-queue/-/p-queue-7.3.0.tgz";
        sha512 = "2sLG0pX2KlvRRv/UXOoZ1tg9w1V2FAerm514BWq1ykNlJPHaIpz0GfbaBWFgCFSlfcaHmxjvs7ZlHtPrPUXWMg==";
      };
    };
    "@esm2cjs/p-timeout-5.1.0" = {
      name = "_at_esm2cjs_slash_p-timeout";
      packageName = "@esm2cjs/p-timeout";
      version = "5.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@esm2cjs/p-timeout/-/p-timeout-5.1.0.tgz";
        sha512 = "QW2sTVKgqiK1nirBD8Sq39izyYj3IINfzwtxn/rpcFjMan7qXovQG3X2SzTsLKxw/phftc2M9Qh4lPtBfb2Bzg==";
      };
    };
    "@esm2cjs/responselike-3.0.0" = {
      name = "_at_esm2cjs_slash_responselike";
      packageName = "@esm2cjs/responselike";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@esm2cjs/responselike/-/responselike-3.0.0.tgz";
        sha512 = "VIQ3pvevlVGC1uzQ7JxCQH3VFmzmC8ASXk35oKq4+VaLBZioKJR/eXk8C7GD8OgajnNByClo/rEsku1fqMTNSw==";
      };
    };
    "@homebridge/ciao-1.1.5" = {
      name = "_at_homebridge_slash_ciao";
      packageName = "@homebridge/ciao";
      version = "1.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@homebridge/ciao/-/ciao-1.1.5.tgz";
        sha512 = "ZI9tcbPfX2d8oP1PNeLzrZLXISAIDUtJQWk4JVVJKCxktC6tQ3JyWXT9t1FbB5xtl82M1jdCgyAbWbjhUtRWcA==";
      };
    };
    "@sentry-internal/tracing-7.47.0" = {
      name = "_at_sentry-internal_slash_tracing";
      packageName = "@sentry-internal/tracing";
      version = "7.47.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@sentry-internal/tracing/-/tracing-7.47.0.tgz";
        sha512 = "udpHnCzF8DQsWf0gQwd0XFGp6Y8MOiwnl8vGt2ohqZGS3m1+IxoRLXsSkD8qmvN6KKDnwbaAvYnK0z0L+AW95g==";
      };
    };
    "@sentry/core-7.47.0" = {
      name = "_at_sentry_slash_core";
      packageName = "@sentry/core";
      version = "7.47.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@sentry/core/-/core-7.47.0.tgz";
        sha512 = "EFhZhKdMu7wKmWYZwbgTi8FNZ7Fq+HdlXiZWNz51Bqe3pHmfAkdHtAEs0Buo0v623MKA0CA4EjXIazGUM34XTg==";
      };
    };
    "@sentry/integrations-7.47.0" = {
      name = "_at_sentry_slash_integrations";
      packageName = "@sentry/integrations";
      version = "7.47.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@sentry/integrations/-/integrations-7.47.0.tgz";
        sha512 = "PUSeBYI3fCOswn+K+PLjtl2epr8/ceqebWqVcxHclczSY3EOZE+osznDFgZmeVgrHavsgfE4oFVqJeFvDJwCog==";
      };
    };
    "@sentry/node-7.47.0" = {
      name = "_at_sentry_slash_node";
      packageName = "@sentry/node";
      version = "7.47.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@sentry/node/-/node-7.47.0.tgz";
        sha512 = "LTg2r5EV9yh4GLYDF+ViSltR9LLj/pcvk8YhANJcMO3Fp//xh8njcdU0FC2yNthUREawYDzAsVzLyCYJfV0H1A==";
      };
    };
    "@sentry/types-7.47.0" = {
      name = "_at_sentry_slash_types";
      packageName = "@sentry/types";
      version = "7.47.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@sentry/types/-/types-7.47.0.tgz";
        sha512 = "GxXocplN0j1+uczovHrfkykl9wvkamDtWxlPUQgyGlbLGZn+UH1Y79D4D58COaFWGEZdSNKr62gZAjfEYu9nQA==";
      };
    };
    "@sentry/utils-7.47.0" = {
      name = "_at_sentry_slash_utils";
      packageName = "@sentry/utils";
      version = "7.47.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@sentry/utils/-/utils-7.47.0.tgz";
        sha512 = "A89SaOLp6XeZfByeYo2C8Ecye/YAtk/gENuyOUhQEdMulI6mZdjqtHAp7pTMVgkBc/YNARVuoa+kR/IdRrTPkQ==";
      };
    };
    "@serialport/binding-mock-10.2.2" = {
      name = "_at_serialport_slash_binding-mock";
      packageName = "@serialport/binding-mock";
      version = "10.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@serialport/binding-mock/-/binding-mock-10.2.2.tgz";
        sha512 = "HAFzGhk9OuFMpuor7aT5G1ChPgn5qSsklTFOTUX72Rl6p0xwcSVsRtG/xaGp6bxpN7fI9D/S8THLBWbBgS6ldw==";
      };
    };
    "@serialport/bindings-cpp-10.8.0" = {
      name = "_at_serialport_slash_bindings-cpp";
      packageName = "@serialport/bindings-cpp";
      version = "10.8.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@serialport/bindings-cpp/-/bindings-cpp-10.8.0.tgz";
        sha512 = "OMQNJz5kJblbmZN5UgJXLwi2XNtVLxSKmq5VyWuXQVsUIJD4l9UGHnLPqM5LD9u3HPZgDI5w7iYN7gxkQNZJUw==";
      };
    };
    "@serialport/bindings-interface-1.2.2" = {
      name = "_at_serialport_slash_bindings-interface";
      packageName = "@serialport/bindings-interface";
      version = "1.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@serialport/bindings-interface/-/bindings-interface-1.2.2.tgz";
        sha512 = "CJaUd5bLvtM9c5dmO9rPBHPXTa9R2UwpkJ0wdh9JCYcbrPWsKz+ErvR0hBLeo7NPeiFdjFO4sonRljiw4d2XiA==";
      };
    };
    "@serialport/parser-byte-length-10.5.0" = {
      name = "_at_serialport_slash_parser-byte-length";
      packageName = "@serialport/parser-byte-length";
      version = "10.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@serialport/parser-byte-length/-/parser-byte-length-10.5.0.tgz";
        sha512 = "eHhr4lHKboq1OagyaXAqkemQ1XyoqbLQC8XJbvccm95o476TmEdW5d7AElwZV28kWprPW68ZXdGF2VXCkJgS2w==";
      };
    };
    "@serialport/parser-cctalk-10.5.0" = {
      name = "_at_serialport_slash_parser-cctalk";
      packageName = "@serialport/parser-cctalk";
      version = "10.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@serialport/parser-cctalk/-/parser-cctalk-10.5.0.tgz";
        sha512 = "Iwsdr03xmCKAiibLSr7b3w6ZUTBNiS+PwbDQXdKU/clutXjuoex83XvsOtYVcNZmwJlVNhAUbkG+FJzWwIa4DA==";
      };
    };
    "@serialport/parser-delimiter-10.5.0" = {
      name = "_at_serialport_slash_parser-delimiter";
      packageName = "@serialport/parser-delimiter";
      version = "10.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@serialport/parser-delimiter/-/parser-delimiter-10.5.0.tgz";
        sha512 = "/uR/yT3jmrcwnl2FJU/2ySvwgo5+XpksDUR4NF/nwTS5i3CcuKS+FKi/tLzy1k8F+rCx5JzpiK+koqPqOUWArA==";
      };
    };
    "@serialport/parser-inter-byte-timeout-10.5.0" = {
      name = "_at_serialport_slash_parser-inter-byte-timeout";
      packageName = "@serialport/parser-inter-byte-timeout";
      version = "10.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@serialport/parser-inter-byte-timeout/-/parser-inter-byte-timeout-10.5.0.tgz";
        sha512 = "WPvVlSx98HmmUF9jjK6y9mMp3Wnv6JQA0cUxLeZBgS74TibOuYG3fuUxUWGJALgAXotOYMxfXSezJ/vSnQrkhQ==";
      };
    };
    "@serialport/parser-packet-length-10.5.0" = {
      name = "_at_serialport_slash_parser-packet-length";
      packageName = "@serialport/parser-packet-length";
      version = "10.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@serialport/parser-packet-length/-/parser-packet-length-10.5.0.tgz";
        sha512 = "jkpC/8w4/gUBRa2Teyn7URv1D7T//0lGj27/4u9AojpDVXsR6dtdcTG7b7dNirXDlOrSLvvN7aS5/GNaRlEByw==";
      };
    };
    "@serialport/parser-readline-10.5.0" = {
      name = "_at_serialport_slash_parser-readline";
      packageName = "@serialport/parser-readline";
      version = "10.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@serialport/parser-readline/-/parser-readline-10.5.0.tgz";
        sha512 = "0aXJknodcl94W9zSjvU+sLdXiyEG2rqjQmvBWZCr8wJZjWEtv3RgrnYiWq4i2OTOyC8C/oPK8ZjpBjQptRsoJQ==";
      };
    };
    "@serialport/parser-ready-10.5.0" = {
      name = "_at_serialport_slash_parser-ready";
      packageName = "@serialport/parser-ready";
      version = "10.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@serialport/parser-ready/-/parser-ready-10.5.0.tgz";
        sha512 = "QIf65LTvUoxqWWHBpgYOL+soldLIIyD1bwuWelukem2yDZVWwEjR288cLQ558BgYxH4U+jLAQahhqoyN1I7BaA==";
      };
    };
    "@serialport/parser-regex-10.5.0" = {
      name = "_at_serialport_slash_parser-regex";
      packageName = "@serialport/parser-regex";
      version = "10.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@serialport/parser-regex/-/parser-regex-10.5.0.tgz";
        sha512 = "9jnr9+PCxRoLjtGs7uxwsFqvho+rxuJlW6ZWSB7oqfzshEZWXtTJgJRgac/RuLft4hRlrmRz5XU40i3uoL4HKw==";
      };
    };
    "@serialport/parser-slip-encoder-10.5.0" = {
      name = "_at_serialport_slash_parser-slip-encoder";
      packageName = "@serialport/parser-slip-encoder";
      version = "10.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@serialport/parser-slip-encoder/-/parser-slip-encoder-10.5.0.tgz";
        sha512 = "wP8m+uXQdkWSa//3n+VvfjLthlabwd9NiG6kegf0fYweLWio8j4pJRL7t9eTh2Lbc7zdxuO0r8ducFzO0m8CQw==";
      };
    };
    "@serialport/parser-spacepacket-10.5.0" = {
      name = "_at_serialport_slash_parser-spacepacket";
      packageName = "@serialport/parser-spacepacket";
      version = "10.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@serialport/parser-spacepacket/-/parser-spacepacket-10.5.0.tgz";
        sha512 = "BEZ/HAEMwOd8xfuJSeI/823IR/jtnThovh7ils90rXD4DPL1ZmrP4abAIEktwe42RobZjIPfA4PaVfyO0Fjfhg==";
      };
    };
    "@serialport/stream-10.5.0" = {
      name = "_at_serialport_slash_stream";
      packageName = "@serialport/stream";
      version = "10.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@serialport/stream/-/stream-10.5.0.tgz";
        sha512 = "gbcUdvq9Kyv2HsnywS7QjnEB28g+6OGB5Z8TLP7X+UPpoMIWoUsoQIq5Kt0ZTgMoWn3JGM2lqwTsSHF+1qhniA==";
      };
    };
    "@types/http-cache-semantics-4.0.1" = {
      name = "_at_types_slash_http-cache-semantics";
      packageName = "@types/http-cache-semantics";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/http-cache-semantics/-/http-cache-semantics-4.0.1.tgz";
        sha512 = "SZs7ekbP8CN0txVG2xVRH6EgKmEm31BOxA07vkFaETzZz1xh+cbt8BcI0slpymvwhx5dlFnQG2rTlPVQn+iRPQ==";
      };
    };
    "@types/triple-beam-1.3.2" = {
      name = "_at_types_slash_triple-beam";
      packageName = "@types/triple-beam";
      version = "1.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/triple-beam/-/triple-beam-1.3.2.tgz";
        sha512 = "txGIh+0eDFzKGC25zORnswy+br1Ha7hj5cMVwKIU7+s0U2AxxJru/jZSMU6OC9MJWP6+pc/hc6ZjyZShpsyY2g==";
      };
    };
    "@zwave-js/cc-10.14.0" = {
      name = "_at_zwave-js_slash_cc";
      packageName = "@zwave-js/cc";
      version = "10.14.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@zwave-js/cc/-/cc-10.14.0.tgz";
        sha512 = "nxJ/gOl1LlrIGiNVOpgHRzjcWJ4YG47RQ27X/IFRKPfuNu+mtuQ5V8OWkzfMRm/fKaMXqezc+k4BDRBPcwJX0Q==";
      };
    };
    "@zwave-js/config-10.14.0" = {
      name = "_at_zwave-js_slash_config";
      packageName = "@zwave-js/config";
      version = "10.14.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@zwave-js/config/-/config-10.14.0.tgz";
        sha512 = "8Cz7+ApTRUbWv27/+wbzwqbY8gicyg7+E7FI6cluBEnfeHTICxECz6zPzhHy+V7lRMlN0OFZ9aCeHUUlpNguvw==";
      };
    };
    "@zwave-js/core-10.14.0" = {
      name = "_at_zwave-js_slash_core";
      packageName = "@zwave-js/core";
      version = "10.14.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@zwave-js/core/-/core-10.14.0.tgz";
        sha512 = "+Wi6MgMrzPufqWIgRg5FQok1vywWFk//IDmuQvKVVJWtk9W8OMBRPTNNnUt957xJ/ebgJngDWXeLCU2USRG+3A==";
      };
    };
    "@zwave-js/host-10.14.0" = {
      name = "_at_zwave-js_slash_host";
      packageName = "@zwave-js/host";
      version = "10.14.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@zwave-js/host/-/host-10.14.0.tgz";
        sha512 = "QBXO9O4HqFB0a+lYCpZxawmlttoWqo9bkhKUUmuTcFLbBAh0qQOq9h8ESxMX+qDnvzMDKMp65UbpFKKIetPKKQ==";
      };
    };
    "@zwave-js/nvmedit-10.14.0" = {
      name = "_at_zwave-js_slash_nvmedit";
      packageName = "@zwave-js/nvmedit";
      version = "10.14.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@zwave-js/nvmedit/-/nvmedit-10.14.0.tgz";
        sha512 = "U0n+0Js5exr4rpzI1aUkdPuFSfanURyP/xJp/VH0bA0IEqlWlbEKS6QgxNBXaNnBJtiqSAaxeGDER5Dl26TrJA==";
      };
    };
    "@zwave-js/serial-10.14.0" = {
      name = "_at_zwave-js_slash_serial";
      packageName = "@zwave-js/serial";
      version = "10.14.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@zwave-js/serial/-/serial-10.14.0.tgz";
        sha512 = "lu0pXiYD+teb2kBEQtmMulmHmbwI4AbX9WQlNu3pU2z3rv39OOhGqz9LCelUzeLJfLa88D7Cs/PtyHIJdOzUdQ==";
      };
    };
    "@zwave-js/shared-10.13.0" = {
      name = "_at_zwave-js_slash_shared";
      packageName = "@zwave-js/shared";
      version = "10.13.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@zwave-js/shared/-/shared-10.13.0.tgz";
        sha512 = "Pt7BL8XcPXVi4Qw7voNFTcuJi4e99MJLFL4HCFmIpLZXe+qwCgBZBDva/Y+uWKBxyaEo6TrZ1V57U9ZcCGJbNQ==";
      };
    };
    "@zwave-js/testing-10.14.0" = {
      name = "_at_zwave-js_slash_testing";
      packageName = "@zwave-js/testing";
      version = "10.14.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@zwave-js/testing/-/testing-10.14.0.tgz";
        sha512 = "Z02VjYoDF+0ZF/6xbDBFXldPZdB65nWEAO/foShO4IGWIG0XGcN3svO/KXzBkdTlWMuB+y69TEomDLWwyzS9Jw==";
      };
    };
    "agent-base-6.0.2" = {
      name = "agent-base";
      packageName = "agent-base";
      version = "6.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/agent-base/-/agent-base-6.0.2.tgz";
        sha512 = "RZNwNclF7+MS/8bDg70amg32dyeZGZxiDuQmZxKLAlQjr3jGyLx+4Kkk58UO7D2QdgFIQCovuSuZESne6RG6XQ==";
      };
    };
    "alcalzone-shared-4.0.8" = {
      name = "alcalzone-shared";
      packageName = "alcalzone-shared";
      version = "4.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/alcalzone-shared/-/alcalzone-shared-4.0.8.tgz";
        sha512 = "Rr0efCjNL9lw7miDvU8exL87Y42ehsLU2jUGNQUphhnlvxnTMrHeApWgoOSGZvsE2PhxC3KO7Z+VpQ/IbuV3aA==";
      };
    };
    "ansi-colors-4.1.3" = {
      name = "ansi-colors";
      packageName = "ansi-colors";
      version = "4.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-colors/-/ansi-colors-4.1.3.tgz";
        sha512 = "/6w/C21Pm1A7aZitlI5Ni/2J6FFQN8i1Cvz3kHABAAbw93v/NlvKdVOqz7CCWz/3iv/JplRSEEZ83XION15ovw==";
      };
    };
    "ansi-regex-5.0.1" = {
      name = "ansi-regex";
      packageName = "ansi-regex";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-5.0.1.tgz";
        sha512 = "quJQXlTSUGL2LH9SUXo8VwsY4soanhgo6LNSm84E1LBcE8s3O0wpdiRzyR9z/ZZJMlMWv37qOOb9pdJlMUEKFQ==";
      };
    };
    "ansi-styles-4.3.0" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "4.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-4.3.0.tgz";
        sha512 = "zbB9rCJAT1rbjiVDb2hqKFHNYLxgtk8NURxZ3IZwD3F6NtxbXZQCnnSi1Lkx+IDohdPlFp222wVALIheZJQSEg==";
      };
    };
    "async-3.2.4" = {
      name = "async";
      packageName = "async";
      version = "3.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/async/-/async-3.2.4.tgz";
        sha512 = "iAB+JbDEGXhyIUavoDl9WP/Jj106Kz9DEn1DPgYw5ruDn0e3Wgi3sKFm55sASdGBNOQB8F59d9qQ7deqrHA8wQ==";
      };
    };
    "axios-0.26.1" = {
      name = "axios";
      packageName = "axios";
      version = "0.26.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/axios/-/axios-0.26.1.tgz";
        sha512 = "fPwcX4EvnSHuInCMItEhAGnaSEXRBjtzh9fOtsE6E1G6p7vl7edEeZe11QHf18+6+9gR5PbKV/sGKNaD8YaMeA==";
      };
    };
    "buffer-from-1.1.2" = {
      name = "buffer-from";
      packageName = "buffer-from";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer-from/-/buffer-from-1.1.2.tgz";
        sha512 = "E+XQCRwSbaaiChtv6k6Dwgc+bx+Bs6vuKJHHl5kox/BaKbhiXzqQOwK4cO22yElGp2OCmjwVhT3HmxgyPGnJfQ==";
      };
    };
    "bufferutil-4.0.7" = {
      name = "bufferutil";
      packageName = "bufferutil";
      version = "4.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/bufferutil/-/bufferutil-4.0.7.tgz";
        sha512 = "kukuqc39WOHtdxtw4UScxF/WVnMFVSQVKhtx3AjZJzhd0RGZZldcrfSEbVsWWe6KNH253574cq5F+wpv0G9pJw==";
      };
    };
    "cliui-8.0.1" = {
      name = "cliui";
      packageName = "cliui";
      version = "8.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/cliui/-/cliui-8.0.1.tgz";
        sha512 = "BSeNnyus75C4//NQ9gQt1/csTXyo/8Sb+afLAkzAptFuMsod9HFokGNudZpi/oQV73hnVK+sR+5PVRMd+Dr7YQ==";
      };
    };
    "color-3.2.1" = {
      name = "color";
      packageName = "color";
      version = "3.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/color/-/color-3.2.1.tgz";
        sha512 = "aBl7dZI9ENN6fUGC7mWpMTPNHmWUSNan9tuWN6ahh5ZLNk9baLJOnSMlrQkHcrfFgz2/RigjUVAjdx36VcemKA==";
      };
    };
    "color-convert-1.9.3" = {
      name = "color-convert";
      packageName = "color-convert";
      version = "1.9.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-convert/-/color-convert-1.9.3.tgz";
        sha512 = "QfAUtd+vFdAtFQcC8CCyYt1fYWxSqAiK2cSD6zDB8N3cpsEBAvRxp9zOGg6G/SHHJYAT88/az/IuDGALsNVbGg==";
      };
    };
    "color-convert-2.0.1" = {
      name = "color-convert";
      packageName = "color-convert";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-convert/-/color-convert-2.0.1.tgz";
        sha512 = "RRECPsj7iu/xb5oKYcsFHSppFNnsj/52OVTRKb4zP5onXwVF3zVmmToNcOfGC+CRDpfK/U584fMg38ZHCaElKQ==";
      };
    };
    "color-name-1.1.3" = {
      name = "color-name";
      packageName = "color-name";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-name/-/color-name-1.1.3.tgz";
        sha512 = "72fSenhMw2HZMTVHeCA9KCmpEIbzWiQsjN+BHcBbS9vr1mtt+vJjPdksIBNUmKAW8TFUDPJK5SUU3QhE9NEXDw==";
      };
    };
    "color-name-1.1.4" = {
      name = "color-name";
      packageName = "color-name";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-name/-/color-name-1.1.4.tgz";
        sha512 = "dOy+3AuW3a2wNbZHIuMZpTcgjGuLU/uBL/ubcZF9OXbDo8ff4O8yVp5Bf0efS8uEoYo5q4Fx7dY9OgQGXgAsQA==";
      };
    };
    "color-string-1.9.1" = {
      name = "color-string";
      packageName = "color-string";
      version = "1.9.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-string/-/color-string-1.9.1.tgz";
        sha512 = "shrVawQFojnZv6xM40anx4CkoDP+fZsw/ZerEMsW/pyzsRbElpsL/DBVW7q3ExxwusdNXI3lXpuhEZkzs8p5Eg==";
      };
    };
    "colorspace-1.1.4" = {
      name = "colorspace";
      packageName = "colorspace";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/colorspace/-/colorspace-1.1.4.tgz";
        sha512 = "BgvKJiuVu1igBUF2kEjRCZXol6wiiGbY5ipL/oVPwm0BL9sIpMIzM8IK7vwuxIIzOXMV3Ey5w+vxhm0rR/TN8w==";
      };
    };
    "cookie-0.4.2" = {
      name = "cookie";
      packageName = "cookie";
      version = "0.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/cookie/-/cookie-0.4.2.tgz";
        sha512 = "aSWTXFzaKWkvHO1Ny/s+ePFpvKsPnjc551iI41v3ny/ow6tBG5Vd+FuqGNhh1LxOmVzOlGUriIlOaokOvhaStA==";
      };
    };
    "cross-spawn-7.0.3" = {
      name = "cross-spawn";
      packageName = "cross-spawn";
      version = "7.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/cross-spawn/-/cross-spawn-7.0.3.tgz";
        sha512 = "iRDPJKUPVEND7dHPO8rkbOnPpyDygcDFtWjpeWNCgy8WP2rXcxXL8TskReQl6OrB2G7+UJrags1q15Fudc7G6w==";
      };
    };
    "dayjs-1.11.7" = {
      name = "dayjs";
      packageName = "dayjs";
      version = "1.11.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/dayjs/-/dayjs-1.11.7.tgz";
        sha512 = "+Yw9U6YO5TQohxLcIkrXBeY73WP3ejHWVvx8XCk3gxvQDCTEmS48ZrSZCKciI7Bhl/uCMyxYtE9UqRILmFphkQ==";
      };
    };
    "debug-4.3.4" = {
      name = "debug";
      packageName = "debug";
      version = "4.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-4.3.4.tgz";
        sha512 = "PRWFHuSU3eDtQJPvnNY7Jcket1j0t5OuOsFzPPzsekD52Zl8qUfFIPEiswXqIvHWGVHOgX+7G/vCNNhehwxfkQ==";
      };
    };
    "decompress-response-6.0.0" = {
      name = "decompress-response";
      packageName = "decompress-response";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/decompress-response/-/decompress-response-6.0.0.tgz";
        sha512 = "aW35yZM6Bb/4oJlZncMH2LCoZtJXTRxES17vE3hoRiowU2kWHaJKFkSBDnDR+cm9J+9QhXmREyIfv0pji9ejCQ==";
      };
    };
    "defer-to-connect-2.0.1" = {
      name = "defer-to-connect";
      packageName = "defer-to-connect";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/defer-to-connect/-/defer-to-connect-2.0.1.tgz";
        sha512 = "4tvttepXG1VaYGrRibk5EwJd1t4udunSOVMdLSAL6mId1ix438oPwPZMALY41FCijukO1L0twNcGsdzS7dHgDg==";
      };
    };
    "emoji-regex-8.0.0" = {
      name = "emoji-regex";
      packageName = "emoji-regex";
      version = "8.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/emoji-regex/-/emoji-regex-8.0.0.tgz";
        sha512 = "MSjYzcWNOA0ewAHpz0MxpYFvwg6yjy1NG3xteoqz644VCo/RPgnr1/GGt+ic3iJTzQ8Eu3TdM14SawnVUmGE6A==";
      };
    };
    "enabled-2.0.0" = {
      name = "enabled";
      packageName = "enabled";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/enabled/-/enabled-2.0.0.tgz";
        sha512 = "AKrN98kuwOzMIdAizXGI86UFBoo26CL21UM763y1h/GMSJ4/OHU9k2YlsmBpyScFo/wbLzWQJBMCW4+IO3/+OQ==";
      };
    };
    "escalade-3.1.1" = {
      name = "escalade";
      packageName = "escalade";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/escalade/-/escalade-3.1.1.tgz";
        sha512 = "k0er2gUkLf8O0zKJiAhmkTnJlTvINGv7ygDNPbeIsX/TJjGJZHuh9B2UxbsaEkmlEo9MfhrSzmhIlhRlI2GXnw==";
      };
    };
    "eventemitter3-4.0.7" = {
      name = "eventemitter3";
      packageName = "eventemitter3";
      version = "4.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/eventemitter3/-/eventemitter3-4.0.7.tgz";
        sha512 = "8guHBZCwKnFhYdHr2ysuRWErTwhoN2X8XELRlrRwpmfeY2jjuUN4taQMsULKUVo1K4DvZl+0pgfyoysHxvmvEw==";
      };
    };
    "execa-5.1.1" = {
      name = "execa";
      packageName = "execa";
      version = "5.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/execa/-/execa-5.1.1.tgz";
        sha512 = "8uSpZZocAZRBAPIEINJj3Lo9HyGitllczc27Eh5YYojjMFMn8yHMDMaUHE2Jqfq05D/wucwI4JGURyXt1vchyg==";
      };
    };
    "fast-deep-equal-3.1.3" = {
      name = "fast-deep-equal";
      packageName = "fast-deep-equal";
      version = "3.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-deep-equal/-/fast-deep-equal-3.1.3.tgz";
        sha512 = "f3qQ9oQy9j2AhBe/H9VC91wLmKBCCU/gDOnKNAYG5hswO7BLKj09Hc5HYNz9cGI++xlpDCIgDaitVs03ATR84Q==";
      };
    };
    "fecha-4.2.3" = {
      name = "fecha";
      packageName = "fecha";
      version = "4.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/fecha/-/fecha-4.2.3.tgz";
        sha512 = "OP2IUU6HeYKJi3i0z4A19kHMQoLVs4Hc+DPqqxI2h/DPZHTm/vjsfC6P0b4jCMy14XizLBqvndQ+UilD7707Jw==";
      };
    };
    "file-stream-rotator-0.6.1" = {
      name = "file-stream-rotator";
      packageName = "file-stream-rotator";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/file-stream-rotator/-/file-stream-rotator-0.6.1.tgz";
        sha512 = "u+dBid4PvZw17PmDeRcNOtCP9CCK/9lRN2w+r1xIS7yOL9JFrIBKTvrYsxT4P0pGtThYTn++QS5ChHaUov3+zQ==";
      };
    };
    "fn.name-1.1.0" = {
      name = "fn.name";
      packageName = "fn.name";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fn.name/-/fn.name-1.1.0.tgz";
        sha512 = "GRnmB5gPyJpAhTQdSZTSp9uaPSvl09KoYcMQtsB9rQoOmzs9dH6ffeccH+Z+cv6P68Hu5bC6JjRh4Ah/mHSNRw==";
      };
    };
    "follow-redirects-1.15.2" = {
      name = "follow-redirects";
      packageName = "follow-redirects";
      version = "1.15.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/follow-redirects/-/follow-redirects-1.15.2.tgz";
        sha512 = "VQLG33o04KaQ8uYi2tVNbdrWp1QWxNNea+nmIB4EVM28v0hmP17z7aG1+wAkNzVq4KeXTq3221ye5qTJP91JwA==";
      };
    };
    "fs-extra-10.1.0" = {
      name = "fs-extra";
      packageName = "fs-extra";
      version = "10.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs-extra/-/fs-extra-10.1.0.tgz";
        sha512 = "oRXApq54ETRj4eMiFzGnHWGy+zo5raudjuxN0b8H7s/RU2oW0Wvsx9O0ACRN/kRq9E8Vu/ReskGB5o3ji+FzHQ==";
      };
    };
    "get-caller-file-2.0.5" = {
      name = "get-caller-file";
      packageName = "get-caller-file";
      version = "2.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-caller-file/-/get-caller-file-2.0.5.tgz";
        sha512 = "DyFP3BM/3YHTQOCUL/w0OZHR0lpKeGrxotcHWcqNEdnltqFwXVfhEBQ94eIo34AfQpo0rGki4cyIiftY06h2Fg==";
      };
    };
    "get-stream-6.0.1" = {
      name = "get-stream";
      packageName = "get-stream";
      version = "6.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-stream/-/get-stream-6.0.1.tgz";
        sha512 = "ts6Wi+2j3jQjqi70w5AlN8DFnkSwC+MqmxEzdEALB2qXZYV3X/b1CTfgPLGJNMeAWxdPfU8FO1ms3NUfaHCPYg==";
      };
    };
    "graceful-fs-4.2.11" = {
      name = "graceful-fs";
      packageName = "graceful-fs";
      version = "4.2.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/graceful-fs/-/graceful-fs-4.2.11.tgz";
        sha512 = "RbJ5/jmFcNNCcDV5o9eTnBLJ/HszWV0P73bc+Ff4nS/rJj+YaS6IGyiOL0VoBYX+l1Wrl3k63h/KrH+nhJ0XvQ==";
      };
    };
    "http-cache-semantics-4.1.1" = {
      name = "http-cache-semantics";
      packageName = "http-cache-semantics";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-cache-semantics/-/http-cache-semantics-4.1.1.tgz";
        sha512 = "er295DKPVsV82j5kw1Gjt+ADA/XYHsajl82cGNQG2eyoPkvgUhX+nDIyelzhIWbbsXP39EHcI6l5tYs2FYqYXQ==";
      };
    };
    "http2-wrapper-2.2.0" = {
      name = "http2-wrapper";
      packageName = "http2-wrapper";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/http2-wrapper/-/http2-wrapper-2.2.0.tgz";
        sha512 = "kZB0wxMo0sh1PehyjJUWRFEd99KC5TLjZ2cULC4f9iqJBAmKQQXEICjxl5iPJRwP40dpeHFqqhm7tYCvODpqpQ==";
      };
    };
    "https-proxy-agent-5.0.1" = {
      name = "https-proxy-agent";
      packageName = "https-proxy-agent";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/https-proxy-agent/-/https-proxy-agent-5.0.1.tgz";
        sha512 = "dFcAjpTQFgoLMzC2VwU+C/CbS7uRL0lWmxDITmqm7C+7F0Odmj6s9l6alZc6AELXhrnggM2CeWSXHGOdX2YtwA==";
      };
    };
    "human-signals-2.1.0" = {
      name = "human-signals";
      packageName = "human-signals";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/human-signals/-/human-signals-2.1.0.tgz";
        sha512 = "B4FFZ6q/T2jhhksgkbEW3HBvWIfDW85snkQgawt07S7J5QXTk6BkNV+0yAeZrM5QpMAdYlocGoljn0sJ/WQkFw==";
      };
    };
    "immediate-3.0.6" = {
      name = "immediate";
      packageName = "immediate";
      version = "3.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/immediate/-/immediate-3.0.6.tgz";
        sha512 = "XXOFtyqDjNDAQxVfYxuF7g9Il/IbWmmlQg2MYKOH8ExIT1qg6xc4zyS3HaEEATgs1btfzxq15ciUiY7gjSXRGQ==";
      };
    };
    "inherits-2.0.4" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.4.tgz";
        sha512 = "k/vGaX4/Yla3WzyMCvTQOXYeIHvqOKtnqBduzTHpzpQZzAskKMhZ2K+EnBiSM9zGSoIFeMpXKxa4dYeZIQqewQ==";
      };
    };
    "is-arrayish-0.3.2" = {
      name = "is-arrayish";
      packageName = "is-arrayish";
      version = "0.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-arrayish/-/is-arrayish-0.3.2.tgz";
        sha512 = "eVRqCvVlZbuw3GrM63ovNSNAeA1K16kaR/LRY/92w0zxQ5/1YzwblUX652i4Xs9RwAGjW9d9y6X88t8OaAJfWQ==";
      };
    };
    "is-fullwidth-code-point-3.0.0" = {
      name = "is-fullwidth-code-point";
      packageName = "is-fullwidth-code-point";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-fullwidth-code-point/-/is-fullwidth-code-point-3.0.0.tgz";
        sha512 = "zymm5+u+sCsSWyD9qNaejV3DFvhCKclKdizYaJUuHA83RLjb7nSuGnddCHGv0hk+KY7BMAlsWeK4Ueg6EV6XQg==";
      };
    };
    "is-stream-2.0.1" = {
      name = "is-stream";
      packageName = "is-stream";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-stream/-/is-stream-2.0.1.tgz";
        sha512 = "hFoiJiTl63nn+kstHGBtewWSKnQLpyb155KHheA1l39uvtO9nWIop1p3udqPcUd/xbF1VLMO4n7OI6p7RbngDg==";
      };
    };
    "isexe-2.0.0" = {
      name = "isexe";
      packageName = "isexe";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isexe/-/isexe-2.0.0.tgz";
        sha512 = "RHxMLp9lnKHGHRng9QFhRCMbYAcVpn69smSGcq3f36xjgVVWThj4qqLbTLlq7Ssj8B+fIQ1EuCEGI2lKsyQeIw==";
      };
    };
    "json-buffer-3.0.1" = {
      name = "json-buffer";
      packageName = "json-buffer";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-buffer/-/json-buffer-3.0.1.tgz";
        sha512 = "4bV5BfR2mqfQTJm+V5tPPdf+ZpuhiIvTuAB5g8kcrXOZpTT/QwwVRWBywX1ozr6lEuPdbHxwaJlm9G6mI2sfSQ==";
      };
    };
    "json-logic-js-2.0.2" = {
      name = "json-logic-js";
      packageName = "json-logic-js";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-logic-js/-/json-logic-js-2.0.2.tgz";
        sha512 = "ZBtBdMJieqQcH7IX/LaBsr5pX+Y5JIW+EhejtM3Ffg2jdN9Iwf+Ht6TbHnvAZ/YtwyuhPaCBlnvzrwVeWdvGDQ==";
      };
    };
    "json5-2.2.3" = {
      name = "json5";
      packageName = "json5";
      version = "2.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/json5/-/json5-2.2.3.tgz";
        sha512 = "XmOWe7eyHYH14cLdVPoyg+GOH3rYX++KpzrylJwSW98t3Nk+U8XOl8FWKOgwtzdb8lXGf6zYwDUzeHMWfxasyg==";
      };
    };
    "jsonfile-6.1.0" = {
      name = "jsonfile";
      packageName = "jsonfile";
      version = "6.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonfile/-/jsonfile-6.1.0.tgz";
        sha512 = "5dgndWOriYSm5cnYaJNhalLNDKOqFwyDB/rr1E9ZsGciGvKPs8R2xYGCacuf3z6K1YKDz182fd+fY3cn3pMqXQ==";
      };
    };
    "keyv-4.5.2" = {
      name = "keyv";
      packageName = "keyv";
      version = "4.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/keyv/-/keyv-4.5.2.tgz";
        sha512 = "5MHbFaKn8cNSmVW7BYnijeAVlE4cYA/SVkifVgrh7yotnfhKmjuXpDKjrABLnT0SfHWV21P8ow07OGfRrNDg8g==";
      };
    };
    "kuler-2.0.0" = {
      name = "kuler";
      packageName = "kuler";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/kuler/-/kuler-2.0.0.tgz";
        sha512 = "Xq9nH7KlWZmXAtodXDDRE7vs6DU1gTU8zYDHDiWLSip45Egwq3plLHzPn27NgvzL2r1LMPC1vdqh98sQxtqj4A==";
      };
    };
    "lie-3.1.1" = {
      name = "lie";
      packageName = "lie";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/lie/-/lie-3.1.1.tgz";
        sha512 = "RiNhHysUjhrDQntfYSfY4MU24coXXdEOgw9WGcKHNeEwffDYbF//u87M1EWaMGzuFoSbqW0C9C6lEEhDOAswfw==";
      };
    };
    "localforage-1.10.0" = {
      name = "localforage";
      packageName = "localforage";
      version = "1.10.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/localforage/-/localforage-1.10.0.tgz";
        sha512 = "14/H1aX7hzBBmmh7sGPd+AOMkkIrHM3Z1PAyGgZigA1H1p5O5ANnMyWzvpAETtG68/dC4pC0ncy3+PPGzXZHPg==";
      };
    };
    "logform-2.5.1" = {
      name = "logform";
      packageName = "logform";
      version = "2.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/logform/-/logform-2.5.1.tgz";
        sha512 = "9FyqAm9o9NKKfiAKfZoYo9bGXXuwMkxQiQttkT4YjjVtQVIQtK6LmVtlxmCaFswo6N4AfEkHqZTV0taDtPotNg==";
      };
    };
    "lowercase-keys-3.0.0" = {
      name = "lowercase-keys";
      packageName = "lowercase-keys";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lowercase-keys/-/lowercase-keys-3.0.0.tgz";
        sha512 = "ozCC6gdQ+glXOQsveKD0YsDy8DSQFjDTz4zyzEHNV5+JP5D62LmfDZ6o1cycFx9ouG940M5dE8C8CTewdj2YWQ==";
      };
    };
    "lru-cache-6.0.0" = {
      name = "lru-cache";
      packageName = "lru-cache";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lru-cache/-/lru-cache-6.0.0.tgz";
        sha512 = "Jo6dJ04CmSjuznwJSS3pUeWmd/H0ffTlkXXgwZi+eq1UCmqQwCh+eLsYOYCwY991i2Fah4h1BEMCx4qThGbsiA==";
      };
    };
    "lru_map-0.3.3" = {
      name = "lru_map";
      packageName = "lru_map";
      version = "0.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/lru_map/-/lru_map-0.3.3.tgz";
        sha512 = "Pn9cox5CsMYngeDbmChANltQl+5pi6XmTrraMSzhPmMBbmgcxmqWry0U3PGapCU1yB4/LqCcom7qhHZiF/jGfQ==";
      };
    };
    "merge-stream-2.0.0" = {
      name = "merge-stream";
      packageName = "merge-stream";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/merge-stream/-/merge-stream-2.0.0.tgz";
        sha512 = "abv/qOcuPfk3URPfDzmZU1LKmuw8kT+0nIHvKrKgFrwifol/doWcdA4ZqsWQ8ENrFKkd67Mfpo/LovbIUsbt3w==";
      };
    };
    "mimic-fn-2.1.0" = {
      name = "mimic-fn";
      packageName = "mimic-fn";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mimic-fn/-/mimic-fn-2.1.0.tgz";
        sha512 = "OqbOk5oEQeAZ8WXWydlu9HJjz9WVdEIvamMCcXmuqUYjTknH/sqsWvhQ3vgwKFRR1HpjvNBKQ37nbJgYzGqGcg==";
      };
    };
    "mimic-response-3.1.0" = {
      name = "mimic-response";
      packageName = "mimic-response";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mimic-response/-/mimic-response-3.1.0.tgz";
        sha512 = "z0yWI+4FDrrweS8Zmt4Ej5HdJmky15+L2e6Wgn3+iK5fWzb6T3fhNFq2+MeTRb064c6Wr4N/wv0DzQTjNzHNGQ==";
      };
    };
    "minimist-1.2.8" = {
      name = "minimist";
      packageName = "minimist";
      version = "1.2.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-1.2.8.tgz";
        sha512 = "2yyAR8qBkN3YuheJanUpWC5U3bb5osDywNB8RzDVlDwDHbocAJveqqj1u8+SVD7jkWT4yvsHCpWqqWqAxb0zCA==";
      };
    };
    "moment-2.29.4" = {
      name = "moment";
      packageName = "moment";
      version = "2.29.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/moment/-/moment-2.29.4.tgz";
        sha512 = "5LC9SOxjSc2HF6vO2CyuTDNivEdoz2IvyJJGj6X8DJ0eFyfszE0QiEd+iXmBvUP3WHxSjFH/vIsA0EN00cgr8w==";
      };
    };
    "ms-2.1.2" = {
      name = "ms";
      packageName = "ms";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.1.2.tgz";
        sha512 = "sGkPx+VjMtmA6MX27oA4FBFELFCZZ4S4XqeGOXCv68tT+jb3vk/RyaKWP0PTKyWtmLSM0b+adUTEvbs1PEaH2w==";
      };
    };
    "node-addon-api-5.1.0" = {
      name = "node-addon-api";
      packageName = "node-addon-api";
      version = "5.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-addon-api/-/node-addon-api-5.1.0.tgz";
        sha512 = "eh0GgfEkpnoWDq+VY8OyvYhFEzBk6jIYbRKdIlyTiAXIVJ8PyBaKb0rp7oDtoddbdoHWhq8wwr+XZ81F1rpNdA==";
      };
    };
    "node-gyp-build-4.6.0" = {
      name = "node-gyp-build";
      packageName = "node-gyp-build";
      version = "4.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-gyp-build/-/node-gyp-build-4.6.0.tgz";
        sha512 = "NTZVKn9IylLwUzaKjkas1e4u2DLNcV4rdYagA4PWdPwW87Bi7z+BznyKSRwS/761tV/lzCGXplWsiaMjLqP2zQ==";
      };
    };
    "npm-run-path-4.0.1" = {
      name = "npm-run-path";
      packageName = "npm-run-path";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/npm-run-path/-/npm-run-path-4.0.1.tgz";
        sha512 = "S48WzZW777zhNIrn7gxOlISNAqi9ZC/uQFnRdbeIHhZhCA6UqpkOT8T1G7BvfdgP4Er8gF4sUbaS0i7QvIfCWw==";
      };
    };
    "nrf-intel-hex-1.3.0" = {
      name = "nrf-intel-hex";
      packageName = "nrf-intel-hex";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/nrf-intel-hex/-/nrf-intel-hex-1.3.0.tgz";
        sha512 = "oXwBJxX/0Jc4fe2Jxjv3Mw9/qw9JdToDLvJuozfVx+twpkc2oSUm8W/OODX6W4kmWOaYA11ORpGLfQ8BP7mndw==";
      };
    };
    "object-hash-2.2.0" = {
      name = "object-hash";
      packageName = "object-hash";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-hash/-/object-hash-2.2.0.tgz";
        sha512 = "gScRMn0bS5fH+IuwyIFgnh9zBdo4DV+6GhygmWM9HyNJSgS0hScp1f5vjtm7oIIOiT9trXrShAkLFSc2IqKNgw==";
      };
    };
    "one-time-1.0.0" = {
      name = "one-time";
      packageName = "one-time";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/one-time/-/one-time-1.0.0.tgz";
        sha512 = "5DXOiRKwuSEcQ/l0kGCF6Q3jcADFv5tSmRaJck/OqkVFcOzutB134KRSfF0xDrL39MNnqxbHBbUUcjZIhTgb2g==";
      };
    };
    "onetime-5.1.2" = {
      name = "onetime";
      packageName = "onetime";
      version = "5.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/onetime/-/onetime-5.1.2.tgz";
        sha512 = "kbpaSSGJTWdAY5KPVeMOKXSrPtr8C8C7wodJbcsd51jRnmD+GZu8Y0VoU6Dm5Z4vWr0Ig/1NKuWRKf7j5aaYSg==";
      };
    };
    "path-key-3.1.1" = {
      name = "path-key";
      packageName = "path-key";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-key/-/path-key-3.1.1.tgz";
        sha512 = "ojmeN0qd+y0jszEtoY48r0Peq5dwMEkIlCOu6Q5f41lfkswXuKtYrhgoTpLnyIcHm24Uhqx+5Tqm2InSwLhE6Q==";
      };
    };
    "proper-lockfile-4.1.2" = {
      name = "proper-lockfile";
      packageName = "proper-lockfile";
      version = "4.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/proper-lockfile/-/proper-lockfile-4.1.2.tgz";
        sha512 = "TjNPblN4BwAWMXU8s9AEz4JmQxnD1NNL7bNOY/AKUzyamc379FWASUhc/K1pL2noVb+XmZKLL68cjzLsiOAMaA==";
      };
    };
    "quick-lru-5.1.1" = {
      name = "quick-lru";
      packageName = "quick-lru";
      version = "5.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/quick-lru/-/quick-lru-5.1.1.tgz";
        sha512 = "WuyALRjWPDGtt/wzJiadO5AXY+8hZ80hVpe6MyivgraREW751X3SbhRvG3eLKOYN+8VEvqLcf3wdnt44Z4S4SA==";
      };
    };
    "readable-stream-3.6.2" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "3.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-3.6.2.tgz";
        sha512 = "9u/sniCrY3D5WdsERHzHE4G2YCXqoG5FTHUiCC4SIbr6XcLZBY05ya9EKjYek9O5xOAwjGq+1JdGBAS7Q9ScoA==";
      };
    };
    "reflect-metadata-0.1.13" = {
      name = "reflect-metadata";
      packageName = "reflect-metadata";
      version = "0.1.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/reflect-metadata/-/reflect-metadata-0.1.13.tgz";
        sha512 = "Ts1Y/anZELhSsjMcU605fU9RE4Oi3p5ORujwbIKXfWa+0Zxs510Qrmrce5/Jowq3cHSZSJqBjypxmHarc+vEWg==";
      };
    };
    "require-directory-2.1.1" = {
      name = "require-directory";
      packageName = "require-directory";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/require-directory/-/require-directory-2.1.1.tgz";
        sha512 = "fGxEI7+wsG9xrvdjsrlmL22OMTTiHRwAMroiEeMgq8gzoLC/PQr7RsRDSTLUg/bZAZtF+TVIkHc6/4RIKrui+Q==";
      };
    };
    "resolve-alpn-1.2.1" = {
      name = "resolve-alpn";
      packageName = "resolve-alpn";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve-alpn/-/resolve-alpn-1.2.1.tgz";
        sha512 = "0a1F4l73/ZFZOakJnQ3FvkJ2+gSTQWz/r2KE5OdDY0TxPm5h4GkqkWWfM47T7HsbnOtcJVEF4epCVy6u7Q3K+g==";
      };
    };
    "responselike-3.0.0" = {
      name = "responselike";
      packageName = "responselike";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/responselike/-/responselike-3.0.0.tgz";
        sha512 = "40yHxbNcl2+rzXvZuVkrYohathsSJlMTXKryG5y8uciHv1+xDLHQpgjG64JUO9nrEq2jGLH6IZ8BcZyw3wrweg==";
      };
    };
    "retry-0.12.0" = {
      name = "retry";
      packageName = "retry";
      version = "0.12.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/retry/-/retry-0.12.0.tgz";
        sha512 = "9LkiTwjUh6rT555DtE9rTX+BKByPfrMzEAtnlEtdEwr3Nkffwiihqe2bWADg+OQRjt9gl6ICdmB/ZFDCGAtSow==";
      };
    };
    "safe-buffer-5.2.1" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.2.1.tgz";
        sha512 = "rp3So07KcdmmKbGvgaNxQSJr7bGVSVk5S9Eq1F+ppbRo70+YeaDxkw5Dd8NPN+GD6bjnYm2VuPuCXmpuYvmCXQ==";
      };
    };
    "safe-stable-stringify-2.4.3" = {
      name = "safe-stable-stringify";
      packageName = "safe-stable-stringify";
      version = "2.4.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-stable-stringify/-/safe-stable-stringify-2.4.3.tgz";
        sha512 = "e2bDA2WJT0wxseVd4lsDP4+3ONX6HpMXQa1ZhFQ7SU+GjvORCmShbCMltrtIDfkYhVHrOcPtj+KhmDBdPdZD1g==";
      };
    };
    "semver-7.3.8" = {
      name = "semver";
      packageName = "semver";
      version = "7.3.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-7.3.8.tgz";
        sha512 = "NB1ctGL5rlHrPJtFDVIVzTyQylMLu9N9VICA6HSFJo8MCGVTMW6gfpicwKmmK/dAjTOrqu5l63JJOpDSrAis3A==";
      };
    };
    "serialport-10.5.0" = {
      name = "serialport";
      packageName = "serialport";
      version = "10.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/serialport/-/serialport-10.5.0.tgz";
        sha512 = "7OYLDsu5i6bbv3lU81pGy076xe0JwpK6b49G6RjNvGibstUqQkI+I3/X491yBGtf4gaqUdOgoU1/5KZ/XxL4dw==";
      };
    };
    "shebang-command-2.0.0" = {
      name = "shebang-command";
      packageName = "shebang-command";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/shebang-command/-/shebang-command-2.0.0.tgz";
        sha512 = "kHxr2zZpYtdmrN1qDjrrX/Z1rR1kG8Dx+gkpK1G4eXmvXswmcE1hTWBWYUzlraYw1/yZp6YuDY77YtvbN0dmDA==";
      };
    };
    "shebang-regex-3.0.0" = {
      name = "shebang-regex";
      packageName = "shebang-regex";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/shebang-regex/-/shebang-regex-3.0.0.tgz";
        sha512 = "7++dFhtcx3353uBaq8DDR4NuxBetBzC7ZQOhmTQInHEd6bSrXdiEyzCvG07Z44UYdLShWUyXt5M/yhz8ekcb1A==";
      };
    };
    "signal-exit-3.0.7" = {
      name = "signal-exit";
      packageName = "signal-exit";
      version = "3.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/signal-exit/-/signal-exit-3.0.7.tgz";
        sha512 = "wnD2ZE+l+SPC/uoS0vXeE9L1+0wuaMqKlfz9AMUo38JsyLSBWSFcHR1Rri62LZc12vLr1gb3jl7iwQhgwpAbGQ==";
      };
    };
    "simple-swizzle-0.2.2" = {
      name = "simple-swizzle";
      packageName = "simple-swizzle";
      version = "0.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/simple-swizzle/-/simple-swizzle-0.2.2.tgz";
        sha512 = "JA//kQgZtbuY83m+xT+tXJkmJncGMTFT+C+g2h2R9uxkYIrE2yy9sgmcLhCnw57/WSD+Eh3J97FPEDFnbXnDUg==";
      };
    };
    "source-map-0.6.1" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.6.1.tgz";
        sha512 = "UjgapumWlbMhkBgzT7Ykc5YXUT46F0iKu8SGXq0bcwP5dz/h0Plj6enJqjz1Zbq2l5WaqYnrVbwWOWMyF3F47g==";
      };
    };
    "source-map-support-0.5.21" = {
      name = "source-map-support";
      packageName = "source-map-support";
      version = "0.5.21";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map-support/-/source-map-support-0.5.21.tgz";
        sha512 = "uBHU3L3czsIyYXKX88fdrGovxdSCoTGDRZ6SYXtSRxLZUzHg5P/66Ht6uoUlHu9EZod+inXhKo3qQgwXUT/y1w==";
      };
    };
    "stack-trace-0.0.10" = {
      name = "stack-trace";
      packageName = "stack-trace";
      version = "0.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/stack-trace/-/stack-trace-0.0.10.tgz";
        sha512 = "KGzahc7puUKkzyMt+IqAep+TVNbKP+k2Lmwhub39m1AsTSkaDutx56aDCo+HLDzf/D26BIHTJWNiTG1KAJiQCg==";
      };
    };
    "string-width-4.2.3" = {
      name = "string-width";
      packageName = "string-width";
      version = "4.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/string-width/-/string-width-4.2.3.tgz";
        sha512 = "wKyQRQpjJ0sIp62ErSZdGsjMJWsap5oRNihHhu6G7JVO/9jIB6UyevL+tXuOqrng8j/cxKTWyWUwvSTriiZz/g==";
      };
    };
    "string_decoder-1.3.0" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-1.3.0.tgz";
        sha512 = "hkRX8U1WjJFd8LsDJ2yQ/wWWxaopEsABU1XfkM8A+j0+85JAGppt16cr1Whg6KIbb4okU6Mql6BOj+uup/wKeA==";
      };
    };
    "strip-ansi-6.0.1" = {
      name = "strip-ansi";
      packageName = "strip-ansi";
      version = "6.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-6.0.1.tgz";
        sha512 = "Y38VPSHcqkFrCpFnQ9vuSXmquuv5oXOKpGeT6aGrr3o3Gc9AlVa6JBfUSOCnbxGGZF+/0ooI7KrPuUSztUdU5A==";
      };
    };
    "strip-final-newline-2.0.0" = {
      name = "strip-final-newline";
      packageName = "strip-final-newline";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-final-newline/-/strip-final-newline-2.0.0.tgz";
        sha512 = "BrpvfNAE3dcvq7ll3xVumzjKjZQ5tI1sEUIKr3Uoks0XUl45St3FlatVqef9prk4jRDzhW6WZg+3bk93y6pLjA==";
      };
    };
    "text-hex-1.0.0" = {
      name = "text-hex";
      packageName = "text-hex";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/text-hex/-/text-hex-1.0.0.tgz";
        sha512 = "uuVGNWzgJ4yhRaNSiubPY7OjISw4sw4E5Uv0wbjp+OzcbmVU/rsT8ujgcXJhn9ypzsgr5vlzpPqP+MBBKcGvbg==";
      };
    };
    "triple-beam-1.3.0" = {
      name = "triple-beam";
      packageName = "triple-beam";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/triple-beam/-/triple-beam-1.3.0.tgz";
        sha512 = "XrHUvV5HpdLmIj4uVMxHggLbFSZYIn7HEWsqePZcI50pco+MPqJ50wMGY794X7AOOhxOBAjbkqfAbEe/QMp2Lw==";
      };
    };
    "tslib-1.14.1" = {
      name = "tslib";
      packageName = "tslib";
      version = "1.14.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/tslib/-/tslib-1.14.1.tgz";
        sha512 = "Xni35NKzjgMrwevysHTCArtLDpPvye8zV/0E4EyYn43P7/7qvQwPh9BGkHewbMulVntbigmcT7rdX3BNo9wRJg==";
      };
    };
    "tslib-2.5.0" = {
      name = "tslib";
      packageName = "tslib";
      version = "2.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/tslib/-/tslib-2.5.0.tgz";
        sha512 = "336iVw3rtn2BUK7ORdIAHTyxHGRIHVReokCR3XjbckJMK7ms8FysBfhLR8IXnAgy7T0PTPNBWKiH514FOW/WSg==";
      };
    };
    "universalify-2.0.0" = {
      name = "universalify";
      packageName = "universalify";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/universalify/-/universalify-2.0.0.tgz";
        sha512 = "hAZsKq7Yy11Zu1DE0OzWjw7nnLZmJZYTDZZyEFHZdUhV8FkH5MCfoU1XMaxXovpyW5nq5scPqq0ZDP9Zyl04oQ==";
      };
    };
    "utf-8-validate-6.0.3" = {
      name = "utf-8-validate";
      packageName = "utf-8-validate";
      version = "6.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/utf-8-validate/-/utf-8-validate-6.0.3.tgz";
        sha512 = "uIuGf9TWQ/y+0Lp+KGZCMuJWc3N9BHA+l/UmHd/oUHwJJDeysyTRxNQVkbzsIWfGFbRe3OcgML/i0mvVRPOyDA==";
      };
    };
    "util-deprecate-1.0.2" = {
      name = "util-deprecate";
      packageName = "util-deprecate";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/util-deprecate/-/util-deprecate-1.0.2.tgz";
        sha512 = "EPD5q1uXyFxJpCrLnCc1nHnq3gOa6DZBocAIiI2TaSCA7VCJ1UJDMagCzIkXNsUYfD1daK//LTEQ8xiIbrHtcw==";
      };
    };
    "which-2.0.2" = {
      name = "which";
      packageName = "which";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/which/-/which-2.0.2.tgz";
        sha512 = "BLI3Tl1TW3Pvl70l3yq3Y64i+awpwXqsGBYWkkqMtnbXgrMD+yj7rhW0kuEDxzJaYXGjEW5ogapKNMEKNMjibA==";
      };
    };
    "winston-3.8.2" = {
      name = "winston";
      packageName = "winston";
      version = "3.8.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/winston/-/winston-3.8.2.tgz";
        sha512 = "MsE1gRx1m5jdTTO9Ld/vND4krP2To+lgDoMEHGGa4HIlAUyXJtfc7CxQcGXVyz2IBpw5hbFkj2b/AtUdQwyRew==";
      };
    };
    "winston-daily-rotate-file-4.7.1" = {
      name = "winston-daily-rotate-file";
      packageName = "winston-daily-rotate-file";
      version = "4.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/winston-daily-rotate-file/-/winston-daily-rotate-file-4.7.1.tgz";
        sha512 = "7LGPiYGBPNyGHLn9z33i96zx/bd71pjBn9tqQzO3I4Tayv94WPmBNwKC7CO1wPHdP9uvu+Md/1nr6VSH9h0iaA==";
      };
    };
    "winston-transport-4.5.0" = {
      name = "winston-transport";
      packageName = "winston-transport";
      version = "4.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/winston-transport/-/winston-transport-4.5.0.tgz";
        sha512 = "YpZzcUzBedhlTAfJg6vJDlyEai/IFMIVcaEZZyl3UXIl4gmqRpU7AE89AHLkbzLUsv0NVmw7ts+iztqKxxPW1Q==";
      };
    };
    "wrap-ansi-7.0.0" = {
      name = "wrap-ansi";
      packageName = "wrap-ansi";
      version = "7.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrap-ansi/-/wrap-ansi-7.0.0.tgz";
        sha512 = "YVGIj2kamLSTxw6NsZjoBxfSwsn0ycdesmc4p+Q21c5zPuZ1pl+NfxVdxPtdHvmNVOQ6XSYG4AUtyt/Fi7D16Q==";
      };
    };
    "ws-8.13.0" = {
      name = "ws";
      packageName = "ws";
      version = "8.13.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ws/-/ws-8.13.0.tgz";
        sha512 = "x9vcZYTrFPC7aSIbj7sRCYo7L/Xb8Iy+pW0ng0wt2vCJv7M9HOMy0UoN3rr+IFC7hb7vXoqS+P9ktyLLLhO+LA==";
      };
    };
    "xstate-4.29.0" = {
      name = "xstate";
      packageName = "xstate";
      version = "4.29.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/xstate/-/xstate-4.29.0.tgz";
        sha512 = "F6WF5s6xG/bm8Oxi2ETuzwGQW8yleL5I4JPxZl49m7Uw7D4LAXu+4dvUK78Uo4D863sM8auqw6+1Xmj9mFlmDQ==";
      };
    };
    "y18n-5.0.8" = {
      name = "y18n";
      packageName = "y18n";
      version = "5.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/y18n/-/y18n-5.0.8.tgz";
        sha512 = "0pfFzegeDWJHJIAmTLRP2DwHjdF5s7jo9tuztdQxAhINCdvS+3nGINqPd00AphqJR/0LhANUS6/+7SCb98YOfA==";
      };
    };
    "yallist-4.0.0" = {
      name = "yallist";
      packageName = "yallist";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/yallist/-/yallist-4.0.0.tgz";
        sha512 = "3wdGidZyq5PB084XLES5TpOSRA3wjXAlIWMhum2kRcv/41Sn2emQ0dycQW4uZXLejwKvg6EsvbdlVL+FYEct7A==";
      };
    };
    "yargs-17.7.1" = {
      name = "yargs";
      packageName = "yargs";
      version = "17.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/yargs/-/yargs-17.7.1.tgz";
        sha512 = "cwiTb08Xuv5fqF4AovYacTFNxk62th7LKJ6BL9IGUpTJrWoU7/7WdQGTP2SjKf1dUNBGzDd28p/Yfs/GI6JrLw==";
      };
    };
    "yargs-parser-21.1.1" = {
      name = "yargs-parser";
      packageName = "yargs-parser";
      version = "21.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/yargs-parser/-/yargs-parser-21.1.1.tgz";
        sha512 = "tVpsJW7DdjecAiFpbIB1e3qxIQsE6NoPc5/eTdrbbIC4h0LVsWhnoa3g+m2HclBIujHzsxZ4VJVA+GUuc2/LBw==";
      };
    };
    "zwave-js-10.14.1" = {
      name = "zwave-js";
      packageName = "zwave-js";
      version = "10.14.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/zwave-js/-/zwave-js-10.14.1.tgz";
        sha512 = "GT+AMNVPwOGpFG2UFZw2l2/PUfHDBddha9S724cY+ZPnzR5iMXBDotF6pzawVTca5vRLF00Zzr2ocwUBje4wew==";
      };
    };
  };
in
{
  "@zwave-js/server" = nodeEnv.buildNodePackage {
    name = "_at_zwave-js_slash_server";
    packageName = "@zwave-js/server";
    version = "1.27.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/@zwave-js/server/-/server-1.27.0.tgz";
      sha512 = "f6J6CsS4UrIMdNtug2P8d/1ELi0iBp2uJnsl/9AIgPS7ikDUOzebFrCsqUHy/2WvRMKbk3DSSpgkKmV+T9WfLw==";
    };
    dependencies = [
      sources."@alcalzone/jsonl-db-3.1.0"
      sources."@alcalzone/pak-0.8.1"
      sources."@alcalzone/proper-lockfile-4.1.3-0"
      sources."@colors/colors-1.5.0"
      sources."@dabh/diagnostics-2.0.3"
      sources."@esm2cjs/cacheable-lookup-7.0.0"
      sources."@esm2cjs/cacheable-request-10.2.8"
      sources."@esm2cjs/form-data-encoder-2.1.4"
      sources."@esm2cjs/got-12.5.3"
      sources."@esm2cjs/http-timer-5.0.1"
      sources."@esm2cjs/is-5.3.0"
      sources."@esm2cjs/lowercase-keys-3.0.0"
      sources."@esm2cjs/mimic-response-4.0.0"
      sources."@esm2cjs/normalize-url-8.0.0"
      sources."@esm2cjs/p-cancelable-3.0.0"
      sources."@esm2cjs/p-queue-7.3.0"
      sources."@esm2cjs/p-timeout-5.1.0"
      sources."@esm2cjs/responselike-3.0.0"
      sources."@homebridge/ciao-1.1.5"
      (sources."@sentry-internal/tracing-7.47.0" // {
        dependencies = [
          sources."tslib-1.14.1"
        ];
      })
      (sources."@sentry/core-7.47.0" // {
        dependencies = [
          sources."tslib-1.14.1"
        ];
      })
      (sources."@sentry/integrations-7.47.0" // {
        dependencies = [
          sources."tslib-1.14.1"
        ];
      })
      (sources."@sentry/node-7.47.0" // {
        dependencies = [
          sources."tslib-1.14.1"
        ];
      })
      sources."@sentry/types-7.47.0"
      (sources."@sentry/utils-7.47.0" // {
        dependencies = [
          sources."tslib-1.14.1"
        ];
      })
      sources."@serialport/binding-mock-10.2.2"
      sources."@serialport/bindings-cpp-10.8.0"
      sources."@serialport/bindings-interface-1.2.2"
      sources."@serialport/parser-byte-length-10.5.0"
      sources."@serialport/parser-cctalk-10.5.0"
      sources."@serialport/parser-delimiter-10.5.0"
      sources."@serialport/parser-inter-byte-timeout-10.5.0"
      sources."@serialport/parser-packet-length-10.5.0"
      sources."@serialport/parser-readline-10.5.0"
      sources."@serialport/parser-ready-10.5.0"
      sources."@serialport/parser-regex-10.5.0"
      sources."@serialport/parser-slip-encoder-10.5.0"
      sources."@serialport/parser-spacepacket-10.5.0"
      sources."@serialport/stream-10.5.0"
      sources."@types/http-cache-semantics-4.0.1"
      sources."@types/triple-beam-1.3.2"
      sources."@zwave-js/cc-10.14.0"
      sources."@zwave-js/config-10.14.0"
      sources."@zwave-js/core-10.14.0"
      sources."@zwave-js/host-10.14.0"
      sources."@zwave-js/nvmedit-10.14.0"
      sources."@zwave-js/serial-10.14.0"
      sources."@zwave-js/shared-10.13.0"
      sources."@zwave-js/testing-10.14.0"
      sources."agent-base-6.0.2"
      sources."alcalzone-shared-4.0.8"
      sources."ansi-colors-4.1.3"
      sources."ansi-regex-5.0.1"
      sources."ansi-styles-4.3.0"
      sources."async-3.2.4"
      sources."axios-0.26.1"
      sources."buffer-from-1.1.2"
      sources."bufferutil-4.0.7"
      sources."cliui-8.0.1"
      (sources."color-3.2.1" // {
        dependencies = [
          sources."color-convert-1.9.3"
          sources."color-name-1.1.3"
        ];
      })
      sources."color-convert-2.0.1"
      sources."color-name-1.1.4"
      sources."color-string-1.9.1"
      sources."colorspace-1.1.4"
      sources."cookie-0.4.2"
      sources."cross-spawn-7.0.3"
      sources."dayjs-1.11.7"
      sources."debug-4.3.4"
      sources."decompress-response-6.0.0"
      sources."defer-to-connect-2.0.1"
      sources."emoji-regex-8.0.0"
      sources."enabled-2.0.0"
      sources."escalade-3.1.1"
      sources."eventemitter3-4.0.7"
      sources."execa-5.1.1"
      sources."fast-deep-equal-3.1.3"
      sources."fecha-4.2.3"
      sources."file-stream-rotator-0.6.1"
      sources."fn.name-1.1.0"
      sources."follow-redirects-1.15.2"
      sources."fs-extra-10.1.0"
      sources."get-caller-file-2.0.5"
      sources."get-stream-6.0.1"
      sources."graceful-fs-4.2.11"
      sources."http-cache-semantics-4.1.1"
      sources."http2-wrapper-2.2.0"
      sources."https-proxy-agent-5.0.1"
      sources."human-signals-2.1.0"
      sources."immediate-3.0.6"
      sources."inherits-2.0.4"
      sources."is-arrayish-0.3.2"
      sources."is-fullwidth-code-point-3.0.0"
      sources."is-stream-2.0.1"
      sources."isexe-2.0.0"
      sources."json-buffer-3.0.1"
      sources."json-logic-js-2.0.2"
      sources."json5-2.2.3"
      sources."jsonfile-6.1.0"
      sources."keyv-4.5.2"
      sources."kuler-2.0.0"
      sources."lie-3.1.1"
      sources."localforage-1.10.0"
      sources."logform-2.5.1"
      sources."lowercase-keys-3.0.0"
      sources."lru-cache-6.0.0"
      sources."lru_map-0.3.3"
      sources."merge-stream-2.0.0"
      sources."mimic-fn-2.1.0"
      sources."mimic-response-3.1.0"
      sources."minimist-1.2.8"
      sources."moment-2.29.4"
      sources."ms-2.1.2"
      sources."node-addon-api-5.1.0"
      sources."node-gyp-build-4.6.0"
      sources."npm-run-path-4.0.1"
      sources."nrf-intel-hex-1.3.0"
      sources."object-hash-2.2.0"
      sources."one-time-1.0.0"
      sources."onetime-5.1.2"
      sources."path-key-3.1.1"
      sources."proper-lockfile-4.1.2"
      sources."quick-lru-5.1.1"
      sources."readable-stream-3.6.2"
      sources."reflect-metadata-0.1.13"
      sources."require-directory-2.1.1"
      sources."resolve-alpn-1.2.1"
      sources."responselike-3.0.0"
      sources."retry-0.12.0"
      sources."safe-buffer-5.2.1"
      sources."safe-stable-stringify-2.4.3"
      sources."semver-7.3.8"
      sources."serialport-10.5.0"
      sources."shebang-command-2.0.0"
      sources."shebang-regex-3.0.0"
      sources."signal-exit-3.0.7"
      sources."simple-swizzle-0.2.2"
      sources."source-map-0.6.1"
      sources."source-map-support-0.5.21"
      sources."stack-trace-0.0.10"
      sources."string-width-4.2.3"
      sources."string_decoder-1.3.0"
      sources."strip-ansi-6.0.1"
      sources."strip-final-newline-2.0.0"
      sources."text-hex-1.0.0"
      sources."triple-beam-1.3.0"
      sources."tslib-2.5.0"
      sources."universalify-2.0.0"
      sources."utf-8-validate-6.0.3"
      sources."util-deprecate-1.0.2"
      sources."which-2.0.2"
      sources."winston-3.8.2"
      sources."winston-daily-rotate-file-4.7.1"
      sources."winston-transport-4.5.0"
      sources."wrap-ansi-7.0.0"
      sources."ws-8.13.0"
      sources."xstate-4.29.0"
      sources."y18n-5.0.8"
      sources."yallist-4.0.0"
      sources."yargs-17.7.1"
      sources."yargs-parser-21.1.1"
      sources."zwave-js-10.14.1"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Full access to zwave-js driver through Websockets";
      homepage = "https://github.com/zwave-js/zwave-js-server#readme";
      license = "Apache-2.0";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
